name: Publish Docker
on: 
  push:
    branches: 
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
       # run: cat ~/my_password.txt | docker login --username foo --password-stdin

